version: "3.8"

services:
  mysql:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_DATABASE: quick_start
      MYSQL_USER: quick_start
      MYSQL_PASSWORD: quick_start
      MYSQL_ROOT_PASSWORD: quick_start
      MYSQL_ROOT_USER: quick_start
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
